CREATE TABLE CrawlerDB.clicks(
ID INT PRIMARY KEY NOT NULL auto_increment, 
NUMBER_OF_CLICKS int NOT NULL,
TODAY_DATE date NOT NULL
);

SELECT * FROM CrawlerDB.clicks;
SELECT * FROM CrawlerDB.clicks WHERE TODAY_DATE BETWEEN '2017-04-19' and '2017-04-29';
DELETE FROM CrawlerDB.clicks WHERE ID=1;
DROP TABLE CrawlerDB.clicks;
TRUNCATE CrawlerDB.clicks;

INSERT INTO CrawlerDB.clicks(NUMBER_OF_CLICKS,TODAY_DATE)VALUES(23,'2017-04-26');
INSERT INTO CrawlerDB.clicks(NUMBER_OF_CLICKS,TODAY_DATE)VALUES(24,'2017-04-27');
INSERT INTO CrawlerDB.clicks(NUMBER_OF_CLICKS,TODAY_DATE)VALUES(6,'2017-04-28');
INSERT INTO CrawlerDB.clicks(NUMBER_OF_CLICKS,TODAY_DATE)VALUES(4,'2017-04-29');
INSERT INTO CrawlerDB.clicks(NUMBER_OF_CLICKS,TODAY_DATE)VALUES(23,'2017-04-24');
INSERT INTO CrawlerDB.clicks(NUMBER_OF_CLICKS,TODAY_DATE)VALUES(5,'2017-04-23');
INSERT INTO CrawlerDB.clicks(NUMBER_OF_CLICKS,TODAY_DATE)VALUES(5,'2017-04-22');
INSERT INTO CrawlerDB.clicks(NUMBER_OF_CLICKS,TODAY_DATE)VALUES(7,'2017-04-21');
INSERT INTO CrawlerDB.clicks(NUMBER_OF_CLICKS,TODAY_DATE)VALUES(60,'2017-04-20');
INSERT INTO CrawlerDB.clicks(NUMBER_OF_CLICKS,TODAY_DATE)VALUES(62,'2017-04-19');